# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='id',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='object_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
